name: Deploy to AWS EKS

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push Backend
      run: |
        docker build -t YOUR_DOCKER_HUB_USERNAME/backend:latest ./backend
        docker push YOUR_DOCKER_HUB_USERNAME/backend:latest

    - name: Build and Push Frontend
      run: |
        docker build -t YOUR_DOCKER_HUB_USERNAME/frontend:latest ./frontend
        docker push YOUR_DOCKER_HUB_USERNAME/frontend:latest

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy to Kubernetes
      run: |
        aws eks update-kubeconfig --region us-east-1 --name my-cluster
        kubectl apply -f backend-deployment.yaml
        kubectl apply -f frontend-deployment.yaml
